### ISSUE TITLE
[Bug] NCCL socketStartConnect fails on specific GPUTEST node during multi-node training

### ISSUE THREAD

**Issue by URRealHero** [TaiMingLu/Della-Manual#2]
When running a multi-node, multi-GPU training job on the debug node **gputest node**. the job fails during the communication initialization. I cannot find the problem, my scripts works well on all other debug nodes, I found it only occur when interact with _**della-l08g**_ nodes. The failure is a ncclSystemError with the message socketStartConnect: ... failed : Software caused connection abort, indicating a network-level problem.

Here is the error:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/sp2526/VecsetV3/hy3dshape/main.py", line 203, in <module>
[rank0]:     trainer.fit(model, datamodule=data, ckpt_path=training_cfg.ckpt_path)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
[rank0]:     return trainer_fn(*args, **kwargs)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
[rank0]:     self._run(model, ckpt_path=self.ckpt_path)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run
[rank0]:     self.__setup_profiler()
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1509, in __setup_profiler
[rank0]:     self.profiler.setup(stage=self.state.fn, local_rank=local_rank, log_dir=self.log_dir)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1826, in log_dir
[rank0]:     dirpath = self.strategy.broadcast(dirpath)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 314, in broadcast
[rank0]:     torch.distributed.broadcast_object_list(obj, src, group=_group.WORLD)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3479, in broadcast_object_list
[rank0]:     broadcast(object_sizes_tensor, src=global_src, group=group)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/sp2526/.conda/ps/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2726, in broadcast
[rank0]:     work = group.broadcast([tensor], opts)
[rank0]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.hpp:268, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
[rank0]: ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
[rank0]: Last error:
[rank0]: socketStartConnect: Connect to 172.28.6.37<54263> failed : Software caused connection abort
```

**Comment by TaiMingLu** [comment]
The issue is a codebase-specific one, and the user solved it by switching to more compatible repo.

A sample script to test your multinode setup:
```bash
#!/bin/bash
#SBATCH -J hy3d-diff-4x4
#SBATCH -N 4                           # <-- NODES (edit to 1/2/4 as needed)
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:4                   # <-- 4 GPUs per node
#SBATCH --constraint=gpu80
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH -t 01:00:00
#SBATCH -o logs_diffusion/%x-%j.out

echo "========================================="
echo "Job started on $(date)"
echo "Node: $(hostname)"
echo "Job ID: $SLURM_JOB_ID"
echo "Node list: $SLURM_JOB_NODELIST"
echo "GPUs per node: ${SLURM_GPUS_ON_NODE}"
echo "========================================="

# ---------- USER KNOBS ----------
CONFIG="configs/unconditional_kl_baseline.yaml"                  # your full config
RUN_NAME="hy3d_uncond_run"                      # tag for this run
OUTPUT_DIR="/scratch/gpfs/ZHUANGL/sp2526/training/outputs_diffusion/${RUN_NAME}"             # Lightning saves logs/ckpts here
USE_BF16=1                                   # 1=bf16, 0=fp32
USE_FAST=1                                   # enable TF32 matmul etc (your --fast)
USE_DEEPSPEED=0                              # 0=DDP, 1=deepspeed_stage_1, 2=stage_2
AUTO_RESUME=1                                # resume from latest ckpt if found
# ----------------------------------

mkdir -p "${OUTPUT_DIR}" logs_diffusion

# Runtime env
export OMP_NUM_THREADS=1
export PYTHONFAULTHANDLER=1

# Triton cache off NFS
export TRITON_CACHE_DIR="/scratch/${USER}/.triton/autotune"
mkdir -p "${TRITON_CACHE_DIR}"

# Rendezvous
MASTER_ADDR=$(scontrol show hostnames "$SLURM_NODELIST" | head -n 1)
MASTER_PORT=$((10000 + SLURM_JOB_ID % 50000))
export MASTER_ADDR MASTER_PORT

# NCCL (tweak if your fabric differs)
export NCCL_DEBUG=INFO
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export NCCL_BLOCKING_WAIT=1
export NCCL_TIMEOUT=600
export PL_TORCH_DISTRIBUTED_TIMEOUT=600
export TORCH_DISTRIBUTED_DEBUG=DETAIL

# Auto-resume: pick the latest *.ckpt under outputs/<RUN_NAME>/ckpt/
CKPT_ARG=""
if [[ "$AUTO_RESUME" == "1" ]]; then
  latest_ckpt="$(ls -1 "${OUTPUT_DIR}"/ckpt/ckpt-*.ckpt 2>/dev/null | sort -V | tail -1)"
  if [[ -n "$latest_ckpt" ]]; then
    echo "[Resume] Found checkpoint: $latest_ckpt"
    CKPT_ARG="--ckpt_path ${latest_ckpt}"
  else
    echo "[Resume] No checkpoint found. Starting fresh."
  fi
else
  echo "[Resume] AUTO_RESUME=0. Starting fresh."
fi

# CLI overrides
precision_flags=""
if [[ "$USE_BF16" == "1" ]]; then
  precision_flags="--use_amp --amp_type bf16"
fi
fast_flag=""
[[ "$USE_FAST" == "1" ]] && fast_flag="--fast"

ds_flag=""
if   [[ "$USE_DEEPSPEED" == "1" ]]; then ds_flag="--deepspeed"
elif [[ "$USE_DEEPSPEED" == "2" ]]; then ds_flag="--deepspeed2"
fi

# Build launch command
LAUNCH_CMD=(
  torchrun
  --nproc_per_node="${SLURM_GPUS_ON_NODE}"
  --nnodes="${SLURM_NNODES}"
  --rdzv_backend=c10d
  --rdzv_endpoint="${MASTER_ADDR}:${MASTER_PORT}"
  main.py
  -c "${CONFIG}"
  --output_dir "${OUTPUT_DIR}"
  --num_nodes "${SLURM_NNODES}"
  --num_gpus "${SLURM_GPUS_ON_NODE}"
  ${fast_flag}
  ${precision_flags}
  ${ds_flag}
  ${CKPT_ARG}
)

echo "========================================="
echo "Launching training:"
printf ' %q' "${LAUNCH_CMD[@]}"; echo
echo "========================================="

# Run
srun "${LAUNCH_CMD[@]}"

echo "========================================="
echo "Job finished on $(date)"
```
